//! The `/var` drain.
//!
//! `/var` must not exist in the commit. Everything a package left there becomes
//! either a `tmpfiles.d` line or a copy under `/usr/share/factory`, and then
//! `/var` is emptied — so a freshly-deployed machine with an empty `/var` comes
//! up correctly, and a machine with existing `/var` state keeps it.
//!
//! Planning and applying are separate. The plan is a value: it can be
//! inspected, snapshotted, and reasoned about without root and without writing
//! anything. If this gets it wrong the symptom is a service that breaks on
//! first boot with a confusing error, which is the worst place to find out.

use crate::tree::{self, Error, Result};
use std::collections::{BTreeMap, BTreeSet};
use std::os::unix::fs::MetadataExt;
use std::path::{Path, PathBuf};

/// Anything larger than this going into the factory earns a warning. it
/// usually means a package is shipping data that should have been in `/usr`,
/// and the image is about to get fat.
pub const FACTORY_WARN_BYTES: u64 = 8 * 1024 * 1024;

/// One line of `/usr/lib/tmpfiles.d/kiln-var.conf`.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum Line {
    /// `d` — recreate a directory.
    Dir {
        path: String,
        mode: u32,
        user: String,
        group: String,
    },
    /// `C` — copy from `/usr/share/factory` if the target does not exist.
    Copy { path: String },
    /// `L` — recreate a symlink.
    ///
    /// Its own case, and the one originally missed: `C`
    /// *stats* the factory path, so a relative link like `/var/lock → ../run/lock`
    /// resolves inside the factory tree, dangles, and systemd-tmpfiles
    /// complains on every boot.
    Link { path: String, target: String },
}

impl Line {
    pub fn path(&self) -> &str {
        match self {
            Line::Dir { path, .. } | Line::Copy { path } | Line::Link { path, .. } => path,
        }
    }

    pub fn render(&self) -> String {
        match self {
            Line::Dir {
                path,
                mode,
                user,
                group,
            } => format!("d {path} {mode:04o} {user} {group} -"),
            Line::Copy { path } => format!("C {path} - - - -"),
            Line::Link { path, target } => format!("L {path} - - - - {target}"),
        }
    }
}

#[derive(Debug, Clone)]
pub struct FactoryCopy {
    /// Absolute, in the staging root.
    pub from: PathBuf,
    /// Absolute, in the staging root, under `usr/share/factory/var`.
    pub to: PathBuf,
    pub mode: u32,
    pub bytes: u64,
}

#[derive(Debug, Clone, Default)]
pub struct Plan {
    pub lines: Vec<Line>,
    pub factory: Vec<FactoryCopy>,
    /// Image paths deliberately not recreated, with the reason.
    pub dropped: Vec<(String, &'static str)>,
    pub warnings: Vec<String>,
}

impl Plan {
    pub fn directories(&self) -> usize {
        self.lines
            .iter()
            .filter(|l| matches!(l, Line::Dir { .. }))
            .count()
    }

    pub fn symlinks(&self) -> usize {
        self.lines
            .iter()
            .filter(|l| matches!(l, Line::Link { .. }))
            .count()
    }

    pub fn factory_bytes(&self) -> u64 {
        self.factory.iter().map(|c| c.bytes).sum()
    }

    /// The body of `/usr/lib/tmpfiles.d/kiln-var.conf`.
    pub fn render(&self) -> String {
        let mut out = String::from(
            "# Generated by Kiln. Recreates /var on a machine whose /var is empty.\n\
             # /var must not exist in the commit.\n",
        );
        for line in &self.lines {
            out.push_str(&line.render());
            out.push('\n');
        }
        out
    }
}

/// Paths dropped entirely rather than drained.
///
/// `/var/lib/pacman` is the one that matters: the `pacman`
/// package **owns** that directory, so relocating the database does not remove
/// it, and a faithful drain would emit a line recreating it on every boot —
/// making the design's own assertion true at build time and false at runtime.
const DROP_ENTIRELY: &[(&str, &str)] = &[
    (
        "/var/lib/pacman",
        "the pacman package owns it; the database is in /usr",
    ),
    (
        "/var/cache/ldconfig",
        "a cache, and it carries wall-clock data",
    ),
];

/// Directories whose *file* contents are not image content. The directories
/// themselves are recreated — services expect them to exist — but what is in
/// them is runtime state that would carry wall-clock data into the commit and
/// make two builds of the same plan differ.
const DROP_FILES_UNDER: &[&str] = &["/var/log"];

/// Directories that must exist on a machine with an empty `/var` even when no
/// package put anything in them. Four of them are the targets of top-level
/// symlinks: without these lines, `/home` points at nothing.
const ALWAYS: &[(&str, u32, &str, &str)] = &[
    ("/var/home", 0o755, "root", "root"),
    ("/var/roothome", 0o700, "root", "root"),
    ("/var/opt", 0o755, "root", "root"),
    ("/var/srv", 0o755, "root", "root"),
    ("/var/mnt", 0o755, "root", "root"),
    // journald fixes its own ACLs, but the emitted line should
    // carry the right group rather than leave it to be corrected. 2755 — setgid
    // — is what systemd's own tmpfiles.d ships.
    ("/var/log/journal", 0o2755, "root", "systemd-journal"),
];

/// Read `<root>/var` and decide the fate of everything in it. Writes nothing.
pub fn plan(root: &Path) -> Result<Plan> {
    let var = root.join("var");
    let users = tree::id_map(&root.join("etc/passwd"));
    let groups = tree::id_map(&root.join("etc/group"));

    let mut plan = Plan::default();
    walk(root, &var, &var, &users, &groups, &mut plan)?;

    // Entries the tree did not supply, added only where the walk produced
    // nothing — a package that shipped `/var/log/journal` with its own mode
    // keeps it.
    let seen: BTreeSet<&str> = plan.lines.iter().map(Line::path).collect();
    let missing: Vec<Line> = ALWAYS
        .iter()
        .filter(|(path, ..)| !seen.contains(path))
        .map(|(path, mode, user, group)| Line::Dir {
            path: (*path).to_string(),
            mode: *mode,
            user: (*user).to_string(),
            group: (*group).to_string(),
        })
        .collect();
    plan.lines.extend(missing);

    // Content-determined order, so two builds of the same tree render the same
    // file. `Line`'s derived ordering sorts by variant first, which would
    // scatter a directory and its children; sorting by path keeps the file
    // readable, and tmpfiles.d creates parents itself so order is not semantic.
    plan.lines
        .sort_by(|a, b| a.path().cmp(b.path()).then_with(|| a.cmp(b)));
    plan.lines.dedup();
    plan.factory.sort_by(|a, b| a.to.cmp(&b.to));
    Ok(plan)
}

fn walk(
    root: &Path,
    var: &Path,
    dir: &Path,
    users: &BTreeMap<u32, String>,
    groups: &BTreeMap<u32, String>,
    plan: &mut Plan,
) -> Result<()> {
    for entry in tree::entries(dir)? {
        let md = entry
            .symlink_metadata()
            .map_err(tree::io("inspecting", &entry))?;
        let rel = entry.strip_prefix(var).expect("walking inside /var");
        let image_path = format!("/var/{}", rel.to_string_lossy());

        // tmpfiles.d is whitespace-separated with no quoting that helps here,
        // so a path containing a space cannot be expressed. Failing is right:
        // silently omitting it would lose the directory at boot.
        if image_path.contains(char::is_whitespace) {
            return Err(tree::shape(format!(
                "`{image_path}` contains whitespace and cannot be expressed in \
                 tmpfiles.d, so /var could not be recreated at boot"
            )));
        }

        if let Some((_, why)) = DROP_ENTIRELY.iter().find(|(p, _)| *p == image_path) {
            plan.dropped.push((image_path, why));
            continue;
        }
        let is_log_content = !md.file_type().is_dir()
            && DROP_FILES_UNDER
                .iter()
                .any(|p| image_path.starts_with(&format!("{p}/")));
        if is_log_content {
            plan.dropped
                .push((image_path, "log content is not image content"));
            continue;
        }

        let user = name_for(users, md.uid());
        let group = name_for(groups, md.gid());
        let mode = md.mode() & 0o7777;

        if md.file_type().is_symlink() {
            let target =
                std::fs::read_link(&entry).map_err(tree::io("reading the link", &entry))?;
            plan.lines.push(Line::Link {
                path: image_path,
                target: target.to_string_lossy().into_owned(),
            });
        } else if md.file_type().is_dir() {
            plan.lines.push(Line::Dir {
                path: image_path,
                mode,
                user,
                group,
            });
            walk(root, var, &entry, users, groups, plan)?;
        } else {
            if md.len() > FACTORY_WARN_BYTES {
                plan.warnings.push(format!(
                    "{image_path} is {} going into /usr/share/factory — a package is \
                     shipping data that belongs in /usr, and the image is about to get fat",
                    tree::human(md.len())
                ));
            }
            plan.factory.push(FactoryCopy {
                from: entry.clone(),
                to: root.join("usr/share/factory/var").join(rel),
                mode,
                bytes: md.len(),
            });
            plan.lines.push(Line::Copy { path: image_path });
        }
    }
    Ok(())
}

fn name_for(map: &BTreeMap<u32, String>, id: u32) -> String {
    map.get(&id).cloned().unwrap_or_else(|| id.to_string())
}

/// Carry the plan out: copy the factory files, write the tmpfiles fragment, and
/// empty `/var`.
pub fn apply(root: &Path, plan: &Plan) -> Result<()> {
    for copy in &plan.factory {
        if let Some(parent) = copy.to.parent() {
            tree::mkdir(parent)?;
        }
        std::fs::copy(&copy.from, &copy.to)
            .map_err(tree::io("copying to the factory", &copy.from))?;
        // `std::fs::copy` carries the mode across on Unix, but saying so
        // explicitly is cheap and the factory's modes are what a first boot
        // installs.
        tree::set_mode(&copy.to, copy.mode)?;
    }

    tree::write(
        &root.join("usr/lib/tmpfiles.d/kiln-var.conf"),
        &plan.render(),
    )?;

    for entry in tree::entries(&root.join("var"))? {
        tree::remove(&entry)?;
    }

    // Defence in depth: the commit filter rejects anything under /var,
    // but a clear failure here beats one from libostree.
    let left = tree::entries(&root.join("var"))?;
    if !left.is_empty() {
        return Err(Error::Shape {
            what: format!("/var is not empty after the drain: {left:?}"),
        });
    }
    Ok(())
}
