//! UID pinning: steps 3 and 4b of assembly. step 3.
//!
//! Arch allocates service-account IDs in `sysusers.d` fragments and package
//! scriptlets, first come first served. Nothing makes the order stable across
//! generations, so `systemd-journal` can be gid 972 in generation 41 and 973 in
//! generation 42 — at which point every file in the persistent
//! `/var/log/journal` is owned by a group that no longer means what it did, and
//! rolling back does not fix it, because `/var` does not roll back.
//!
//! The fix is to replay: capture the IDs a generation ended up with, and seed
//! them into the next one before any package can allocate. The mechanism is
//! entirely internal — there is no configuration surface, because there is no
//! decision for the user to make.
//!
//! Why this needs the transaction split: `/etc/passwd` and
//! `/etc/group` are owned by the `filesystem` package. Seeding before it is
//! installed makes pacman abort on a file conflict, and `--overwrite` would let
//! the stock files clobber the pins. So `filesystem` goes in alone, the seed
//! runs against the passwd it brought, and everything else follows.

use crate::tree::{self, Result};
use kiln_resolve::{IdEntry, UidMap};
use std::path::Path;

/// Anything at or above this is a login account, which Kiln does not manage at
/// all. An image should contain none; the bound is here so that a
/// hand-modified staging root cannot smuggle one into the record.
pub const SYSTEM_MAX: u32 = 999;

/// Where the seed lands. The name matters: `sysusers.d` fragments are processed
/// in lexicographic order and the *first* declaration of a name wins, so this
/// has to sort before anything a package ships. `kiln-pinned` beats every
/// package fragment in Arch today, all of which start with a letter after `k`
/// or with a digit — but the leading `00-` makes it true by construction
/// rather than by luck.
pub const SEED_PATH: &str = "usr/lib/sysusers.d/00-kiln-pinned.conf";

/// Render the seed. Pure, so the exact bytes that decide a generation's account
/// layout can be read in a test rather than inferred from a filesystem.
///
/// Groups come first, and every `u` line names its group by name rather than by
/// number, because sysusers requires the gid a `u` line mentions to be created
/// by some line — and a name that a `g` line above already created always is.
pub fn render_seed(map: &UidMap) -> String {
    let mut out = String::from(
        "# Generated by Kiln. IDs replayed from the previous generation so that\n\
         # persistent /var content keeps meaning what it meant.\n\
         # Not user-editable: this file is rewritten from the build record.\n",
    );
    for (name, gid) in &map.groups {
        out.push_str(&format!("g {name} {gid}\n"));
    }
    for (name, entry) in &map.users {
        // Falling back to the number is not a nicety. A user whose primary
        // group is not in the map at all is one whose group a *package* will
        // create; pinning the number keeps the two consistent, and inventing a
        // group name here would create a second group at the same gid.
        let group = match map.group_at(entry.gid) {
            Some(group) => group.to_string(),
            None => entry.gid.to_string(),
        };
        let home = blank_to_dash(&entry.home);
        let shell = blank_to_dash(&entry.shell);
        out.push_str(&format!(
            "u {name} {}:{group} - {home} {shell}\n",
            entry.uid
        ));
    }
    out
}

fn blank_to_dash(s: &str) -> &str {
    if s.is_empty() {
        "-"
    } else {
        s
    }
}

/// Write the seed and materialize it into the staging root's `passwd`/`group`.
///
/// `systemd-sysusers` is the host's, pointed at the staging root with `--root`.
/// It has to be: at this point the only package installed is `filesystem`, so
/// the staging root has no systemd to run. This is safe in a way that running a
/// *package's* code from the host would not be — sysusers reads declarative
/// fragments and writes account files, and the fragments it reads here are
/// Kiln's own.
pub fn seed(root: &Path, map: &UidMap, sysusers: &dyn Sysusers) -> Result<()> {
    if map.is_empty() {
        // Generation 1. Nothing to replay, and an empty fragment would still be
        // a file in the image claiming to pin something.
        return Ok(());
    }
    tree::write(&root.join(SEED_PATH), &render_seed(map))?;
    sysusers.run(root)
}

/// Running `systemd-sysusers --root` is the one thing in this module that
/// touches the world. Behind a trait so the seed's *content* can be tested
/// without it, and so a test can assert that it was called with the staging
/// root rather than with `/`.
pub trait Sysusers {
    fn run(&self, root: &Path) -> Result<()>;
}

/// The real one.
pub struct HostSysusers;

impl Sysusers for HostSysusers {
    fn run(&self, root: &Path) -> Result<()> {
        let output = std::process::Command::new("systemd-sysusers")
            .arg("--root")
            .arg(root)
            .output()
            .map_err(tree::io("running systemd-sysusers against", root))?;
        if !output.status.success() {
            return Err(tree::shape(format!(
                "systemd-sysusers --root {} failed: {}",
                root.display(),
                String::from_utf8_lossy(&output.stderr).trim()
            )));
        }
        Ok(())
    }
}

/// Read back the accounts the assembled tree actually has ("after the
/// transaction, Kiln diffs the resulting passwd/group against the seed").
///
/// Called after the main transaction and before `/etc` moves to `/usr/etc`, so
/// the paths are still `etc/`.
pub fn capture(root: &Path) -> UidMap {
    let mut map = UidMap::default();

    for fields in colon_lines(&root.join("etc/group")) {
        let (Some(name), Some(Ok(gid))) = (fields.first(), fields.get(2).map(|s| s.parse::<u32>()))
        else {
            continue;
        };
        if gid > SYSTEM_MAX {
            continue;
        }
        map.groups.insert(name.clone(), gid);
    }

    for fields in colon_lines(&root.join("etc/passwd")) {
        let (Some(name), Some(Ok(uid)), Some(Ok(gid))) = (
            fields.first(),
            fields.get(2).map(|s| s.parse::<u32>()),
            fields.get(3).map(|s| s.parse::<u32>()),
        ) else {
            continue;
        };
        if uid > SYSTEM_MAX {
            continue;
        }
        map.users.insert(
            name.clone(),
            IdEntry {
                uid,
                gid,
                home: fields.get(5).cloned().unwrap_or_default(),
                shell: fields.get(6).cloned().unwrap_or_default(),
            },
        );
    }

    map
}

/// A pin the assembled tree did not honor.
///
/// The rule here is to warn rather than fail. An ID that could not be replayed is bad
/// news about `/var`, but refusing to build leaves the user with no image and
/// no way forward, and the drift is already in the tree by the time it is
/// visible.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Drift {
    /// The account is gone. Whatever it owns in the persistent `/var` is now
    /// owned by a number with no name.
    Vanished { account: String, was: String },
    Moved {
        account: String,
        was: String,
        now: String,
    },
}

impl Drift {
    pub fn account(&self) -> &str {
        match self {
            Drift::Vanished { account, .. } | Drift::Moved { account, .. } => account,
        }
    }

    pub fn describe(&self) -> String {
        match self {
            Drift::Vanished { account, was } => format!(
                "{account} was pinned to {was} but is not in the image at all; \
                 anything in /var owned by it is now orphaned"
            ),
            Drift::Moved { account, was, now } => format!(
                "{account} was pinned to {was} but the image allocated {now}; \
                 existing /var content owned by it will be misattributed"
            ),
        }
    }
}

/// Compare what was seeded against what the tree ended up with.
///
/// Only the numbers are compared. A home or shell that moved is a package
/// changing its mind about an account, which is legitimate and not drift.
pub fn drift(seed: &UidMap, actual: &UidMap) -> Vec<Drift> {
    let mut out = Vec::new();
    for (account, gid) in &seed.groups {
        match actual.groups.get(account) {
            Some(got) if got == gid => {}
            Some(got) => out.push(Drift::Moved {
                account: account.clone(),
                was: format!("gid {gid}"),
                now: format!("gid {got}"),
            }),
            None => out.push(Drift::Vanished {
                account: account.clone(),
                was: format!("gid {gid}"),
            }),
        }
    }
    for (account, entry) in &seed.users {
        let was = format!("{}:{}", entry.uid, entry.gid);
        match actual.users.get(account) {
            Some(got) if got.uid == entry.uid && got.gid == entry.gid => {}
            Some(got) => out.push(Drift::Moved {
                account: account.clone(),
                was,
                now: format!("{}:{}", got.uid, got.gid),
            }),
            None => out.push(Drift::Vanished {
                account: account.clone(),
                was,
            }),
        }
    }
    out.sort_by(|a, b| a.account().cmp(b.account()));
    out
}

fn colon_lines(path: &Path) -> Vec<Vec<String>> {
    let Ok(text) = std::fs::read_to_string(path) else {
        return Vec::new();
    };
    text.lines()
        .filter(|l| !l.trim().is_empty() && !l.starts_with('#'))
        .map(|l| l.split(':').map(|f| f.to_string()).collect())
        .collect()
}
