# Terracotta's branding assets.
kiln = 1

[[packages.file]]
path = "https://github.com/Terracotta-Linux/terracotta-branding/releases/latest/download/terracotta-branding-any.pkg.tar.zst"
sha256 = "https://github.com/Terracotta-Linux/terracotta-branding/releases/latest/download/terracotta-branding-any.pkg.tar.zst.sha256"
